// Generate hpu email
const generateHpuEmail = () => {
    const hpuNum = hpuAssem.buildPartNum();
    const hpuBody = genHpuEmailBody();
    const valveBody = genValveEmailBody();
    const totalCostBody = genHpuTotalCostEmailBody();

    const header = `SUN COAST PART CONFIGURATOR`;
    const introMsgHtml = `\n\nA new part number has been generated by ${contactInputs.contactName}!`
    const contactHtml = genContactEmailBody();
    const noteMsgHtml = `\n\nNOTE TO CUSTOMER: \nA customer representative will follow up shortly to provide lead times and to assist in placing your order. `;
    const thankYouMsg = `\n\nThank you for using the Sun Coast Part Configurator!`;

    const emailAddress = defaultEmail;
    const emailSubject = `Sun Coast Part Number Configurator: ${hpuNum}`;
    const bodyText = `${header + introMsgHtml + contactHtml + hpuBody + valveBody + totalCostBody + noteMsgHtml + thankYouMsg}`;

    const mailtoLink = createMailtoLink(emailAddress, emailSubject, bodyText);

    window.location.href = mailtoLink;
};

// Generate hpu email body text
const genHpuEmailBody = () => {

    // Build part num html
    const partNum = hpuAssem.buildPartNum();
    const partNumHtml = `\n\nHPU NUMBER: ${partNum}`;

    // Build hpu cost html
    const cost = parseFloat(hpuAssem.calcCost());
    const costHtml = `\nHPU Assembly List Price: $${cost.toFixed(2)}`;

    const html = partNumHtml + costHtml;

    return html;
};

// Generate valve email body text
const genValveEmailBody = () => {
    let html = '';

    if(valveAssem.station0.valve == null){
        return html;
    }else{
        html += `\n\nVALVE STATIONS:`
        for(i = 0; i < hpuInputs.numStat; i++){
            let station = `station${i}`;
            let valve = valveAssem[station].valve;
            let flowControl = valveAssem[station].flowControl;
            let checkValve = valveAssem[station].checkValve;
    
            html += `\nStation ${i + 1}: ${valve.code}-${flowControl.code}-${checkValve.code}`;
        };
    };

    // Build valve cost html
    const cost = parseFloat(valveAssem.calcCost());
    costHtml = `\nValve Assembly List Price: $${cost.toFixed(2)}`;

    html += costHtml;

    return html;
};

// Generate HPU total cost email body text
const genHpuTotalCostEmailBody = () => {

    const total = calcTotalHpuCost();

    html = `\n\nTOTAL LIST PRICE: $${total.toFixed(2)}`;

    return html;
};